#pragma once
/*////////////////////////////////////////////////////////////////////////////
Token.h

Represents a token generated by a lexer (Tokeniser).

Copyright 2018 HJA Bird

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/////////////////////////////////////////////////////////////////////////////

#include <string>

namespace HBTK {
	class Token {
	public:
		const std::string & value() const;
		const int line() const;

		bool isnum() const;
		bool isvar() const;
		bool isstr() const;
		bool ispunct() const;
		bool isspace() const;

		bool isbracket() const;
		bool isnewline() const;

	private:
		friend class Tokeniser;
		// This is evaluated by the tokeniser
		enum type {
			STRING,
			VARIABLE,
			NUMBER,
			PUNCTUATION,
			WHITE_SPACE
		};

		type m_token_type;
		std::string m_value;
		int m_line;
	};
}